### ISSUE TITLE
Invalid HTTP method: PATCH

### ISSUE THREAD

**Issue by BndyNet** [BndyNet/web-framework-for-java#4]
```java
HttpEntity<?> request = new HttpEntity<Category>(category);
ResponseEntity<Category> c = this.restTemplate.exchange("/api/categories/" + category.getId(), HttpMethod.PATCH, request, Category.class); 
```
## Errors

org.springframework.web.client.ResourceAccessException: I/O error on PATCH request for "http://localhost:59175/api/categories/11": Invalid HTTP method: PATCH; nested exception is java.net.ProtocolException: `Invalid HTTP method: PATCH`
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:666)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531)
	at org.springframework.boot.test.web.client.TestRestTemplate.exchange(TestRestTemplate.java:739)
	at net.bndy.wf.test.CategoryControllerTest.testHttpPatch(CategoryControllerTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
...

**Comment by BndyNet** [comment]
The "PATCH" is non-standard HTTP method.

There is a Won't Fix bug in OpenJDK for this: https://bugs.openjdk.java.net/browse/JDK-7016595

However, with Apache Http-Components Client 4.2+ this is possible. It has a custom networking implementation, thus using non-standard HTTP methods like PATCH is possible. It even has a HttpPatch class supporting the patch method.

```java
CloseableHttpClient httpClient = HttpClients.createDefault();
HttpPatch httpPatch = new HttpPatch(new URI("http://example.com"));
CloseableHttpResponse response = httpClient.execute(httpPatch);
```

Maven Coordinates:

```xml
<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpclient</artifactId>
    <version>4.2+</version>
</dependency>
```
